### ISSUE TITLE
Configure the region resources are deployed in

### ISSUE THREAD

**Issue by thomastoye** [backupfire/backupfire-firebase#3]
My Firestore data is in `europe-west3`. With GDPR compliance and cross-region costs, I'd like to deploy the resources in the EU. Looking through the code, I don't see a way to specify the `region` (`defaultRegion` is set to `us-central1`). Is there a way to configure this?

**Comment by kossnocorp** [comment]
Hey Thomas! So far nobody requested it, but as you see there's a code in place for that. I'm going to add this feature right away 🚧

Thank you so much for your feedback!

**Comment by kossnocorp** [comment]
I've shipped `@backupfire/firebase@0.13.0` that allows specifying the region:

```ts
import backupfireAgent from '@backupfire/firebase'

export const backupfire = backupfireAgent({
  // See the list of available regions:
  // https://firebase.google.com/docs/functions/locations
  region: 'europe-west3'
})
```

Please note that `europe-west3` is available only with the latest `firebase-functions@3.6`.

**Comment by thomastoye** [comment]
Hi Sasha, seems to work now, thanks!

**Comment by kossnocorp** [comment]
@thomastoye awesome 🙌
