### ISSUE TITLE
Memory option not working

### ISSUE THREAD

**Issue by ljle** [backupfire/backupfire-firebase#32]
Hey @kossnocorp, thanks for making this tool. I've been using it for a while now and haven't had any issues up until now.

The recently added memory option doesn't seem to be working, I've tried re-deploying my `backupfire` function multiple times but it just doesn't change from the default memory allocated (`256MB`).

Here is a screenshot from the Firebase functions dahsboard:

![image](https://user-images.githubusercontent.com/696474/106311811-7a0e7c80-6244-11eb-9ca0-3959c020fe93.png)

Here is another one from the Google Cloud Functions console:

![image](https://user-images.githubusercontent.com/696474/106311503-053b4280-6244-11eb-962e-26e48c85758d.png)

Here is how I'm calling it in `functions/index.js`:

![image](https://user-images.githubusercontent.com/696474/106311344-c1483d80-6243-11eb-9068-7368604a5167.png)
![image](https://user-images.githubusercontent.com/696474/106311321-b9889900-6243-11eb-8d1a-89baa8555155.png)

Screenshot from `functions/package.json`:
![image](https://user-images.githubusercontent.com/696474/106313353-d07cba80-6246-11eb-9c7a-8c02eb455b93.png)

Am I missing something here?

Thanks!

**Comment by kossnocorp** [comment]
This is definitely a bug. I'm looking into it.

**Comment by kossnocorp** [comment]
Sorry about that. It turned that the memory option is parsed during the initial code evaluation on the deploying machine, not in the Functions environment. Fixed that and shipped `@backupfire/firebase@1.0.3`.

**Comment by ljle** [comment]
Awesome, thanks for the prompt response 👌

**Comment by kossnocorp** [comment]
@ljle no worries, you're welcome!
